//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALOJAMIENTO
    {
        public int AlojamientoId { get; set; }
        public int ReservaId { get; set; }
        public int HotelId { get; set; }
        public int nro_Hab { get; set; }
    
        public virtual HOTEL HOTEL { get; set; }
        public virtual RESERVA RESERVA { get; set; }

        
    }
}
