//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITINERARIO
    {
        public int ITINERARIOId { get; set; }
        public int ReservaId { get; set; }
        public string origen { get; set; }
        public string destino { get; set; }
        public System.DateTime fec_Salida { get; set; }
        public System.DateTime fec_Retorno { get; set; }
        public int distancia { get; set; }
    
        public virtual RESERVA RESERVA { get; set; }
    }
}
