//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPOTELEFONO
    {
        public int TipoTelefonoId { get; set; }
        public int TelefonoId { get; set; }
        public string tipoTelefono1 { get; set; }
    
        public virtual TELEFONO TELEFONO { get; set; }
    }
}
